services:
  bot:
    build: .
    command: bash -c "alembic upgrade head && poetry run python bot"
    env_file: ".bot-env-prod"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:alpine"
    env_file: ".bot-env-prod"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
