[project]
name = "telegrinder-alchemy"
version = "0.1.0"
description = "Add your description here"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.1",
    "betterconf>=4.5.0",
    "psycopg[binary,pool]>=3.2.9",
    "ruff>=0.11.13",
    "sqlalchemy[asyncio]>=2.0.41",
    "telegrinder",
]

[tool.setuptools.packages.find]
where = ["."] # Look in the current directory
include = ["bot*"] # Only include things that start with 'bot'
# exclude = ["migrations*"] # Explicitly exclude 'migrations' if needed

[tool.uv.sources]
telegrinder = { git = "https://github.com/timoniq/telegrinder", rev = "dev" }
